// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] configuration loader for multi-platform Firebase initialization.
///
/// Automatically resolves and returns platform-specific credentials
/// (Web, Android, iOS, macOS, and Windows) for seamless app connection.
class DefaultFirebaseOptions {
  /// Returns the appropriate [FirebaseOptions] configuration based on the active runtime platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration options for Web platform target.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_API_KEY_HERE',
    messagingSenderId: 'YOUR_API_KEY_HERE',
    projectId: 'save-a-bite-46cda',
    authDomain: 'save-a-bite-46cda.firebaseapp.com',
    storageBucket: 'save-a-bite-46cda.firebasestorage.app',
  );

  /// Firebase configuration options for Android platform target.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_API_KEY_HERE',
    messagingSenderId: 'YOUR_API_KEY_HERE',
    projectId: 'save-a-bite-46cda',
    storageBucket: 'save-a-bite-46cda.firebasestorage.app',
  );

  /// Firebase configuration options for iOS platform target.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_API_KEY_HERE',
    messagingSenderId: 'YOUR_API_KEY_HERE',
    projectId: 'save-a-bite-46cda',
    storageBucket: 'save-a-bite-46cda.firebasestorage.app',
    iosBundleId: 'com.example.saveABite',
  );

  /// Firebase configuration options for macOS platform target.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_API_KEY_HERE',
    messagingSenderId: 'YOUR_API_KEY_HERE',
    projectId: 'save-a-bite-46cda',
    storageBucket: 'save-a-bite-46cda.firebasestorage.app',
    iosBundleId: 'com.example.saveABite',
  );

  /// Firebase configuration options for Windows platform target.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_API_KEY_HERE',
    messagingSenderId: 'YOUR_API_KEY_HERE',
    projectId: 'save-a-bite-46cda',
    authDomain: 'save-a-bite-46cda.firebaseapp.com',
    storageBucket: 'save-a-bite-46cda.firebasestorage.app',
  );
}
